apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
spec:
  containers:
    - resources:
       limits:
          memory: "200Mi"
          cpu: "2"
       requests:
          memory: "100Mi"
          cpu: "2"  
      name: my-app
      image: my-app
      imagePullPolicy: IfNotPresent
  nodeSelector:
    reserved: reserved
  priorityClassName: critical-priority
